### ISSUE TITLE
Ошибка вызова функции acf_form_head() при добавлении персоны 

### ISSUE THREAD

**Issue by Almax** [systemo-biz/casepress#11]
При попытке просмотра созданной персоны выдает - Fatal error: Call to undefined function acf_form_head()

и при попытке добавить медиафайл на странице добавления персоны

консоль firefox Nightly выдает
- ReferenceError: acf is not defined 
- TypeError: e is undefined  - load-scripts.php?…:882 

консоль Opera 28 
- Uncaught ReferenceError: acf is not defined 
- Uncaught TypeError: Cannot read property hasClass of undefined..... load-scripts.php?…:882

**Comment by Dimasmagadan** [comment]
эта функция есть в плагине Advanced Custom Fields
скорее всего у них этот плагин так же используется. попробуйте его поставить, ошибка должна пропасть, либо вызвать новые)

**Comment by yumashev** [comment]
да, обходное решение это поставить Advanced Custom Fields.
но в следующих версиях поправим и добавим проверку

**Comment by Dimasmagadan** [comment]
как добавить проверку чуть выше написал, но нужно протестировать, вдруг что-то другое отвалится

**Comment by yumashev** [comment]
Да, заметил. Выглядит правильно. Протестим :) Спасибо!
