### ISSUE TITLE
Некорректная ссылка на инструкцию в описании CasePress 

### ISSUE THREAD

**Issue by stasparshin** [systemo-biz/casepress#13]
Здравствуйте!
Тут https://github.com/systemo-biz/casepress в п.3 ссылка на шпаргалку ведет на пост в блоге про конверсию.

**Comment by Oleg0s** [comment]
Присоединяюсь,
вот эта ссылка http://casepress.org/kb/shpargalka/

**Comment by yumashev** [comment]
исправили на http://casepress.org/shpargalka/
