### ISSUE TITLE
Тестовое

### ISSUE THREAD

**Issue by Zalki-Lab** [systemo-biz/casepress#26]
1. Одиночная страница http://luger-luger.rhcloud.com/?cinema=the-big-bang-theory
2. Вывод всех custom posts http://luger-luger.rhcloud.com/?post_type=cinema
3. С bootstrap и иконками http://luger-luger.rhcloud.com/?page_id=28
4. Код плагина:
http://pastebin.com/pJ3b8rti
http://pastebin.com/APY5kza3

**Comment by web2033** [comment]
@Zalki-Lab привет, тебе сюда видимо https://github.com/systemo-biz/test/issues

**Comment by yumashev** [comment]
ну да. перепутал продукт. 
тут такое публиковать не надо.
