### ISSUE TITLE
Автокомментарий при выборе ответственного

### ISSUE THREAD

**Issue by yumashev** [systemo-biz/casepress#50]
При добавлении дела можно указать ответственного.

Если ответственный изменен, то добавить комментарий, в котором указать текст:

"@login назначен ответственным по делу"

Где @login это логин пользвателя персоны которая назначена ответственным.

**Comment by Petro-1** [comment]
@yumashev Сделал, проверьте, пожалуйста https://github.com/Petro-1/casepress-usercomments

**Comment by yumashev** [comment]
круто :)
но две логические ошибки:
1. автором коммента логичней назначать текущего пользователя
2. логин без @

**Comment by yumashev** [comment]
и пчм то ссылка на профиль редактирования пользователя публикуется
![image](https://cloud.githubusercontent.com/assets/1852897/13580544/9f801594-e4c4-11e5-93d0-e6694c9425af.png)

**Comment by yumashev** [comment]
@login нужен не просто так, а птм что по этому ключу срабатывает отедльный плагин который отправляет уведомление этому пользователю. Без собаки этот плагин не поймет что надо отправить уведомление.

**Comment by yumashev** [comment]
и это, давай заканчивать щелкать задачи как орешки. Надо оставить другим стажерам чуть чуть :)

**Comment by Petro-1** [comment]
Переделал. Ссылку сделал на посты пользователя (?author=ID). Или вообще убрать ссылки?

**Comment by yumashev** [comment]
вообще убрать

**Comment by Petro-1** [comment]
сделал

**Comment by Petro-1** [comment]
Убрал недоработку с добавлением коммента при удалении ответственного.

**Comment by yumashev** [comment]
очень круто!
