### ISSUE TITLE
Админка или фронтэнд?

### ISSUE THREAD

**Issue by almays** [systemo-biz/casepress#55]
Вопрос до установки.

Ваша система работает в админке или во фронтэнде? В смысле экологично ли её установить на существующий блог, или лучше сделать отдельный wordpress только для casepress, потому что фронтэнд во всю будет задействован элементами системы?

**Comment by yumashev** [comment]
Отдельный сайт лучше. Это не простая система. Для её работы нужны все ресурсы и станицы сайта. Не стоит её ни с чем мешать
