### ISSUE TITLE
Почему casepress нет в официальном репозитории Wordpress?

### ISSUE THREAD

**Issue by nikolozij** [systemo-biz/casepress#60]
Недавно обнаружил вашу систему. Идея понравилась. Почему casepress нет в официальном репозитории Wordpress? Из-за статуса бэта? Так же не нашёл перевода на английский язык. Если бы всё это было пользователей и разработчиков думаю прибавилось бы и развитие пошло бы быстрей.

**Comment by aiiddqd** [comment]
Это экспериментальная разработка. У нее почти нет шансов стать популярной или рентабельной. Потому пока просто лежит тут. Для научного интереса :)
