### ISSUE TITLE
В чём заключается функционал ECM?

### ISSUE THREAD

**Issue by nikolozij** [systemo-biz/casepress#61]
<a href="http://casepress.org/">Здесь</a> сказано, что в casepress реализован функционал ECM, но в чём он заключается я не совсем понял. До этого я пользовался плагинами WP Documents Revisions для контроля версий загруженных документов, надстройка на этот плагин WP Documents Revisions Simle Downloads расширяющий функционал добавления файлов на сайт. Но эти плагины давно не развиваються авторами хотя потенциал у них большой, так же в них не хватает фронт энда. И плагин members позволяет разграничить права доступа пользователей к различным документам и разделам. На этих плагинах я сделал систему электронного документооборота. Если объединить функционал casepress и вышеназванных плагинов, думаю система получилась бы более универсальной и востребованной.

**Comment by aiiddqd** [comment]
ECM - это управление корпоративной информацией (конетнтом).
Управление документами - это микрочасть ECM. Далеко не всем компаниям это надо.
И часто можно найти более эффективные решения.
Разработка такого функционала теоретически возможна. Либо если найдется заказчик. Либо если найдется сумасшедший исследователь-программист :)
