### ISSUE TITLE
Создать хук для подключения полей к комментариям

### ISSUE THREAD

**Issue by yumashev** [systemo-biz/casepress#7]
Проблема:
Сейчас используется стандартный хук подключения полей к комментам, что исключяет возможность указания своего порядка.
Нужно добавить хук, который позволит подключать свои поля как список.

Требования:
- подключить конструкцию типа <div id="cp_comment_form_actions"><ul></ul></div>  и внутрь добавить хук add_comment_action_cp
- в качестве примера использования отдельным файлом добавить подключение поля закрытия дела и указания результата
-- при комментарии пользователь может поставить галочку "Закрыть дело"
-- при указании галочки плавно появляется поле "Укажите результат" и дропдаун выбора термина таксономии results
-- при отправке формы коммента результат указывается у дела (дело это тип поста)
-- если результат уже указан то галочка должна звучать как "Возобновить дело"
-- если указана галочка возобновить дело, то результат у дела отменяется
- добавить описание хука и пример в базу знаний http://casepress.org/kb/

**Comment by yumashev** [comment]
Имелось ввиду то просто упаковать в div с классом и ul
чтобы затем через хук добавлять li теги

**Comment by yumashev** [comment]
Надо упаковать это в плагин.
Плагин выложи на ГитХаб.
Никакие файлы править нельзя. Ни тему, ни другие плагины.
Включаем плагин - заработало.
Выключаем - перетсало работать.
И все.

**Comment by dmnbars** [comment]
https://github.com/dmnbars/casepress-issues-7

**Comment by yumashev** [comment]
вот это ужасно https://github.com/dmnbars/casepress-issues-7/blob/master/commentAction.php#L9

переделай на нормальный html через ob_start
вот статья http://wpcraft.ru/vy-vod-html-echo-i-shablonov-cherez-shortkod-v-wordpress/

**Comment by dmnbars** [comment]
Переделал.

**Comment by yumashev** [comment]
Не вижу хука.
Покажи пример того как мне добавить новый пункт в список?

**Comment by yumashev** [comment]
Лучше одной функцией сделать заделку под хук.
А далее тут же показать как этот хук использовать. Добавив пункт в список.

**Comment by dmnbars** [comment]
Было как раз ощущение, что логика решения не совсем верная.
Переделал.
Новые поля добавляются через хук. В данном случае закрыть/открыть через add_custom_fields.
что бы добавить новый пункт, можно либо дописать код в эту же функцию, либо использовать новый хук, как пример add_another_field.

**Comment by yumashev** [comment]
Вот теперь увидел. И понял что ты пытаешься это делать фильтром. Усложняешь.
Сделай событием. add_action.
Так чтобы не заморачиваться с return. Писать чистый HTML и не вникать во всякие циклы.

**Comment by dmnbars** [comment]
Переделал с использованием add_action.

**Comment by yumashev** [comment]
Так на много интересней :)

**Comment by yumashev** [comment]
А нет. Поторопились.
Где дропдаун выбора терминов?
Надо выбрать один из существующих терминов. А не зашивать в код что то жестко.
Состав терминов же может меняться.

**Comment by dmnbars** [comment]
Сейчас используются метки, т.е. выбор должен осуществляться из существующих меток?
И если пост имеет любую метку, то галочка звучит как "Возобновить дело" и отправлении коммента с установленной галочкой снимаются все метки?

**Comment by yumashev** [comment]
совершенно верно

**Comment by dmnbars** [comment]
Доделал.

**Comment by yumashev** [comment]
Усложнил.
Есть готовый метод http://wp-kama.ru/function/wp_dropdown_categories

**Comment by dmnbars** [comment]
С ним гораздо проще :)

**Comment by yumashev** [comment]
Хук какой то хрупкий. Походу ты поля начал менять. А они не всегда выводятся. Например если пользователь авторизован. Да и это хук фильтр, что тоже для этой задачи сильно тяжело, сложно и глючно. Он не для этого нужен.
Перепиши по аналогии с этим https://github.com/systemo-biz/cp-timesheet/blob/master/cp-timesheet.php#L25

**Comment by dmnbars** [comment]
Да, я добавлял хуком конструкцию к дефолтному значению $defaults['comment_notes_after'], что бы поля выводились до кнопки отправки комментария.
Переделал через add_action, но теперь они выводятся после этой кнопки

**Comment by yumashev** [comment]
Во. Уже что то видно )
И это что то показывает два косяка:
1. Поле не скрыто. Надо чтобы оно появлялось по нажатию галочки.
2. Должен быть пустой выбор. В функции есть такая опция. Суть в том что если я сейас коммент отправлю то какой то термин привяжется. А 80% комментов идут без указания результата. Указание результата должно быть опцией.

**Comment by dmnbars** [comment]
1. Сделал скрытие/показ через JS или есть какой-то встроенный в wp метод? (так же, используется onpropertychange для поддержки старых IE8-, нужно ли это?)
2. Не совсем понял, сейчас используется проверка установки галочки чекбокса с лейблом "Закрыть дело" (isset($_POST['closeCase']) и, если она не установлена, то никакая метка не привязывается.

**Comment by dmnbars** [comment]
1. Или если предполагается использование bootstrap, то могу переписать с его использованием, без добавления на страницу своих js скриптов.

**Comment by yumashev** [comment]
JS тут даже не нужен. Это сложно и дорого.
Хватит пары CSS строк.
Но если не знаешь как, то пока обойдемся таким.

**Comment by yumashev** [comment]
Еще минус JS в том что применяется style атрибут. А это повлечет нарушение W3C валидации если будем делать внешний сайт.

**Comment by yumashev** [comment]
Но как быстрое решение часто используем, потому пока пойдет. Главное осозновать что это быстро, но не оптимально :)

**Comment by dmnbars** [comment]
Через CSS можно используя что-то вроде
#closeCase:checked ~ .result_select_container {
  display: block;
}
Но такое сработает ведь только если оба элемента будут в одно li

То что не оптимально, да, понятно :)

**Comment by yumashev** [comment]
Ты чертовски прав :)
Это и есть ключевая ошибка. Нарушение декомпозиции списка.
Вот правило декомпозиции деревьев http://casepress.org/mece
Этому правилу подчинено все что мы делаем.
Научишься правильно декомпозировать деревья - считай в дамках. Любые задачи любого масштаба и сложности будут тебе по плечу.

**Comment by dmnbars** [comment]
Т.е. ошибка в том, что чекбокс и дропдаун разнесены в разные li, хотя по факту являются чем-то единым?

**Comment by yumashev** [comment]
Совершенно верно. Представь DOM дерево как некий список элементов.
Представь что ты это элементы. Ты единое целое и состоишь из других элементов. Таких как голова и рукиноги.
Рядом с тобой есть кто то еще. Другие люди. Они тоже элементы которые состоят из других элементов.
Так вот ты взял, отпилил себе туловище и поставил рядо в один список с другими людями. Сделал вид что тебя как бы двое в списке. Но это не так.

**Comment by dmnbars** [comment]
Ага, понял.

Вернул себе туловище :)

**Comment by yumashev** [comment]
Щас буду ругаться ))
1. скрипты можно писать в тело, стили нет. стили тока в шапку. потому я и писал что это чуть сложнее. уж лучше на скрипты переделай https://github.com/dmnbars/casepress-issues-7/blob/master/commentAction.php#L30
2. будь то скрипт или стиль. почему ты его поместил в один уровень дерева с элементами? разве он не относится к конкретному элементу? разве он не должен быть частью элемента? а получается что он не часть, а сосед. нарушение декомпозиции.

**Comment by dmnbars** [comment]
1. Изначально потому и сделал через скрипт, так как не знаю для данного случая как вставить стиль не в тело.
2. Переделал. Скрипт поставил в конец элемента для простоты.

Элемент дропдаун скрыл через скрипт, что бы не писать в сам элемент style.

**Comment by yumashev** [comment]
Хрень какую то придумал.
Должно хватить обычного хука comment_form. Главное подключать туда HTML в div обертке.
