### ISSUE TITLE
Первая версия страницы планировщика

### ISSUE THREAD

**Issue by yumashev** [systemo-biz/casepress#8]
- Пока делаем шорткодом и отдельным плагином (ссылку на плагин добавить в комменты к этой странице)
- Секция "Просроченные дела", если есть, выводим первые 5 и возможность подгрузить еще, сортировка по сроку
- Секция "Срочные дела", если есть, выводим первые 5 и возможность подгрузить еще, если есть, сортировка по сроку
- Секция "Дела по приоритету", выводим дела в порядке приоритета (приоритет задаем в метаполе "_cp_order_person_[id]")
- Дела по приоритету можно таскать посредством компонента https://github.com/johnny/jquery-sortable (пример https://github.com/systemo-biz/todo-comments-cp)
- Сверху шорткода можно выбрать персону по которой будем показывать дела, если персона не выбрана, то показываем по текущей персоне

**Comment by lipkij** [comment]
Требуется уточнение,
шорткод по кодексу - это ведь преимущественно инструмент для использования в постах или страницах, в в сайдбарах необходимо использовать виджеты?
То есть эта фишка будет именно элементом страницы или сообщения, а не виджетом? а то меня терзают смутные сомнения

**Comment by lipkij** [comment]
дата закрытия дела - это метаполе? как реализовано? где посмотреть?
Срочность - определяется только датой окончания или еще приоритетом?

**Comment by yumashev** [comment]
шорткод по кодексу - это ведь преимущественно инструмент для использования в постах или страницах, в в сайдбарах необходимо использовать виджеты?
То есть эта фишка будет именно элементом страницы или сообщения, а не виджетом? а то меня терзают смутные сомнения

Изначально как бы да, но их часто применяют в виджетах. Это допустимо, хоть и в каких то ситуациях может вызывать проблемы. Но при желании эти проблемы легко обходятся зная что шорткод будет применяться в виджетах.

**Comment by yumashev** [comment]
//
дата закрытия дела - это метаполе? как реализовано? где посмотреть?
Срочность - определяется только датой окончания или еще приоритетом?
//

дата закрытия хранится так http://casepress.org/kb/blog/data-zakrytiya-hranitsya-v-mete-s-klyuchem-cp_date_end/
срок хранится так http://casepress.org/kb/blog/meta-deadline_cp-hranit-srok-dela/

**Comment by yumashev** [comment]
@lipkij как успехи?
