### ISSUE TITLE
Белый экран при активации плагина casepress

### ISSUE THREAD

**Issue by volkys** [systemo-biz/casepress#9]
Свежая установка по шпаргалке http://new.casepress.org/?page_id=204 до пункта "Включить постоянные ссылки". Дальше картинок нет.

Wordpress v4.1
CasePress v20150109
Apache/2.2.22 (FreeBSD) PHP/5.2.17
Версия MySQL-клиента: 5.1.55

после активации плагина админка работает, а сам сайт выдает "белый экран". Принудительное отображение ошибок через .htaccess ничего не показывает.

Подскажите, куда копать.

**Comment by yumashev** [comment]
Нужно включить debug и посомтреть что пишет в log
О том как это сделать можно почитать тут http://codex.wordpress.org/Debugging_in_WordPress
Или тут https://wpmag.ru/2013/otladka-wordpress-debug-bar/

**Comment by volkys** [comment]
Ай! Забыл про это. Извините.
Notice: Trying to get property of non-object in /public_html/wp-content/plugins/casepress/cp-includes/notice/notice-page/add_notification_list.php on line 46

Notice: Trying to get property of non-object in /public_html/wp-content/plugins/casepress/cp-includes/notice/notice-page/add_notification_list.php on line 46

**Comment by yumashev** [comment]
От этой ошибки не должна система выдавать белый экран.
Исправим в ближайших версиях.
А обойти можно выбором страницы вот тут http://monosnap.com/image/YaDgXsqiDBVgFQAhv53pqwY7kBAjdl

**Comment by yumashev** [comment]
Мб причина в php
5.2 слишком мало.
Лучше 5.3 или 5.4

**Comment by volkys** [comment]
Уточнил у хостинг-провайдера (Peterhost) сайт использует PHP 5.4, phpMyAdmin 5.2.17
но, беда продолжает развиваться. Ваша рекомендация не помогла. Ткнул в раздел Оргструктура и вот http://take.ms/T4KTC
Похоже, я где-то чего-то не довел до ума все-таки. В шпаргалке все действия не выполнил, ибо картинок нету :) Может там загвоздка?

**Comment by yumashev** [comment]
Это та же беда.
Такие уведомления постоянно выводятся. Когда плагины среднего качества или в бета тесте.
Потому можно включить молчаливый режим отладки.
define('WP_DEBUG', true);
define('WP_DEBUG_LOG', true);
define('WP_DEBUG_DISPLAY', false);

Таким образом в файл лог будет писаться, а на экран нет.

**Comment by volkys** [comment]
А может я лучше потестирую? Никогда этим не занимался. Но при моем появлении обычно ломается то, что может сломаться. Правда, я сразу и чиню...

**Comment by yumashev** [comment]
Можно и так

**Comment by yumashev** [comment]
Удалось решить проблему?

**Comment by volkys** [comment]
Скажем так. Удалось локализовать некоторую особенность. Если все делать, как в шпаргалке, не удаляя образцов страницы, комментария и записи, то ошибка не возникает. Но как только удалил, даже, если потом добавил другую страницу, то падает. Более подробно разобраться не удалось, к сожалению. Пришлось отвлечься на рутину. Позже чуток.
